[build]
  publish = "build/web"
  functions = "netlify/functions"
  command = "[ -d \"_flutter\" ] || git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter && ./_flutter/bin/flutter build web --release --no-tree-shake-icons"

[[redirects]]
  from = "/api/google-reviews"
  to = "/.netlify/functions/google-reviews"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
